"use client"
import "./globals.css";
import "./responsive.css";
import { Roboto } from "next/font/google";
import Navbar from "./components/navbar/page";
import 'bootstrap/dist/css/bootstrap.css';

// import dynamic from 'next/dynamic';

// const DynamicBootstrap = dynamic(
//   () => require('bootstrap/dist/js/bootstrap.min.js'),
//   { ssr: false }
// );



const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Dashboard Next.js ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="w-100 border border-2 border-danger">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
