import "./globals.css";
import "./responsive.css";
import { Roboto } from "next/font/google";

import Navbar from "./components/navbar/Navbar";
import "bootstrap/dist/css/bootstrap.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Dashboard Next.js ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="w-100">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
